[project]
name = "transformerxl-ppo-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "chex>=0.1.91",
    "craftax>=1.5.0",
    "distrax>=0.1.5",
    "einops>=0.8.2",
    "flax>=0.12.3",
    "gymnasium>=1.2.3",
    "gymnax>=0.0.8",
    "jax>=0.8.2",
    "kiwisolver>=1.4.9",
    "matplotlib>=3.10.8",
    "optax>=0.2.6",
    "orbax-checkpoint>=0.11.0",
    "rich-argparse>=1.7.2",
    "seaborn>=0.13.2",
    "simple-parsing>=0.1.8",
]


[dependency-groups]
# on rorqual for instance, still necessary to use cuda12
# TODO: Look into an environment variable that could be set in the job script to select the group used based on which cluster we're on?
# OR, perhaps better, specify some arguments to be passed to `uv run` via the cluv config for a particular cluster?
cuda12 = ["jax[cuda12]>=0.9.0.1"]
cuda13 = ["jax[cuda13]>=0.9.0.1"]


[tool.uv]
conflicts = [[{ group = "cuda12" }, { group = "cuda13" }]]

# TODO: Would it be better to setup a default group that works on most clusters?
# default-groups = ["cuda12"]


[tool.uv.sources]
# cluv = { path = "../cluv", editable = true }

[tool.cluv]
clusters = [
    "mila",
    "tamia",
    "narval",
    "rorqual",
    "fir",
    # "nibi",  getting weird errors with nibi, (bash: line 1: git-receive-pack: command not found)
    "killarney",
    "vulcan",
    # "trillium",
    "trillium-gpu",
]
# TODO: Make it possible to use a list of directories or a glob pattern.
# TODO: If we want checkpoints to be stored in a file relative to the project root,
# then we need to adapt the code to recreate this symlink when the jobs start, because if we 
# use safe_sbatch + the code_checkpointing script, the repo is cloned in $SLURM_TMPDIR, and if
# the logs are saved in that directory using a relative path, they will be lost when the job finishes!
results_path = "logs"

# Could be useful to be able to set where the symlink should be pointing to on each cluster.

# [tool.cluv.cluster.tamia]
# gres = "gpu:h100:4"
