[project]
name = "transformerxl-ppo-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "chex>=0.1.91",
    "cluv",
    "craftax>=1.5.0",
    "distrax>=0.1.5",
    "einops>=0.8.2",
    "flax>=0.12.3",
    "gymnasium>=1.2.3",
    "gymnax>=0.0.8",
    "jax>=0.8.2",
    "kiwisolver>=1.4.9",
    "matplotlib>=3.10.8",
    "optax>=0.2.6",
    "orbax-checkpoint>=0.11.0",
    "seaborn>=0.13.2",
    "simple-parsing>=0.1.8",
]

[tool.uv.sources]
# cluv = { path = "../cluv", editable = true }


[dependency-groups]
cuda12 = ["jax[cuda12]>=0.9.0.1"]
cuda13 = ["jax[cuda13]>=0.9.0.1"]

[tool.cluv]
clusters = [
    "mila",
    "tamia",
    "narval",
    "rorqual",
    "fir",
    # "nibi",  getting weird errors with nibi, (bash: line 1: git-receive-pack: command not found)
    "killarney",
    "vulcan",
    "trillium",
    "trillium-gpu",
]
# TODO: Make it possible to use a list of directories or a glob pattern.
results_path = "logs"

# [tool.cluv.cluster.tamia]
# gres = "gpu:h100:4"

[tool.uv]
conflicts = [[{ group = "cuda12" }, { group = "cuda13" }]]
