activation: relu
anneal_lr: true
clip_eps: 0.2
embed_size: 256
ent_coef: 0.002
env_name: craftax
gae_lambda: 0.8
gamma: 0.999
gating: true
gating_bias: 2.0
hidden_layers: 256
lr: 0.0002
max_grad_norm: 1.0
minibatch_size: 0
num_envs: 1024
num_heads: 8
num_layers: 2
num_minibatches: 8
num_steps: 128
num_updates: 0
qkv_features: 256
seed: 0
total_timesteps: 1000000000
update_epochs: 4
vf_coef: 0.5
window_grad: 64
window_mem: 128
